import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

/**
 * Server-side PDF for a generated tenancy agreement (M1-W3-03).
 * Rendered to a buffer in the generate action, never in the browser.
 *
 * Uses the built-in Helvetica family only — no external font fetch, so it
 * renders offline and inside the serverless sandbox with no network.
 */

export interface TenancyAgreementPdfData {
  version: number;
  generatedAt: string; // DD/MM/YYYY
  property: {
    address: string;
    typeLabel: string;
  };
  landlordName: string;
  tenantNames: string[];
  term: {
    startDate: string; // DD/MM/YYYY
    endDate: string; // DD/MM/YYYY
    monthlyRent: string; // S$1,234
    deposit: string; // S$1,234
  };
  clauses: { clause_id: string; title: string; body: string }[];
}

const styles = StyleSheet.create({
  page: {
    paddingTop: 56,
    paddingHorizontal: 56,
    paddingBottom: 72,
    fontFamily: "Helvetica",
    fontSize: 10.5,
    lineHeight: 1.5,
    color: "#1E293B",
  },
  coverTitle: { fontSize: 22, fontFamily: "Helvetica-Bold", lineHeight: 1.2, marginBottom: 6 },
  coverSubtitle: { fontSize: 12, color: "#64748B", marginBottom: 32 },
  coverLabel: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  coverValue: { fontSize: 12, marginBottom: 16 },
  coverRow: { flexDirection: "row", gap: 40 },
  coverCol: { flex: 1 },
  clauseTitle: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    marginTop: 16,
    marginBottom: 6,
  },
  paragraph: { marginBottom: 6, textAlign: "justify" },
  listItem: { flexDirection: "row", marginBottom: 4 },
  listNumber: { width: 20 },
  listBody: { flex: 1, textAlign: "justify" },
  bold: { fontFamily: "Helvetica-Bold" },
  sectionHeading: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginTop: 8,
    marginBottom: 12,
  },
  sigIntro: { marginBottom: 20, color: "#334155" },
  sigBlock: { marginBottom: 28 },
  sigRole: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#64748B",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  sigName: { fontSize: 11, marginBottom: 18 },
  sigLineRow: { flexDirection: "row", gap: 24 },
  sigLineCol: { flex: 1 },
  sigLine: { borderTopWidth: 1, borderTopColor: "#94A3B8", paddingTop: 3 },
  sigLineLabel: { fontSize: 8.5, color: "#64748B" },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 56,
    right: 56,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 0.5,
    borderTopColor: "#CBD5E1",
    paddingTop: 6,
    fontSize: 8,
    color: "#94A3B8",
  },
});

/** Renders `**bold**` inside a clause line; nothing else is inline-styled. */
function InlineText({ text }: { text: string }) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);
  return (
    <>
      {parts.map((part, i) =>
        part.startsWith("**") && part.endsWith("**") ? (
          <Text key={i} style={styles.bold}>
            {part.slice(2, -2)}
          </Text>
        ) : (
          <Text key={i}>{part}</Text>
        )
      )}
    </>
  );
}

/** Splits a clause body (blank-line-separated blocks; `1.` numbered items). */
function ClauseBody({ body }: { body: string }) {
  const blocks = body.split(/\n\s*\n/);
  return (
    <>
      {blocks.map((block, bi) => {
        const lines = block
          .split("\n")
          .map((l) => l.trim())
          .filter(Boolean);
        return lines.map((line, li) => {
          const item = /^(\d+)\.\s+(.*)$/.exec(line);
          if (item) {
            return (
              <View key={`${bi}-${li}`} style={styles.listItem} wrap={false}>
                <Text style={styles.listNumber}>{item[1]}.</Text>
                <Text style={styles.listBody}>
                  <InlineText text={item[2]!} />
                </Text>
              </View>
            );
          }
          return (
            <Text key={`${bi}-${li}`} style={styles.paragraph}>
              <InlineText text={line} />
            </Text>
          );
        });
      })}
    </>
  );
}

function Footer() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by RentOwl — not legal advice</Text>
      <Text
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}

function SignatureBlock({ role, name }: { role: string; name: string }) {
  return (
    <View style={styles.sigBlock} wrap={false}>
      <Text style={styles.sigRole}>{role}</Text>
      <Text style={styles.sigName}>{name}</Text>
      <View style={styles.sigLineRow}>
        <View style={styles.sigLineCol}>
          <View style={styles.sigLine}>
            <Text style={styles.sigLineLabel}>Signature</Text>
          </View>
        </View>
        <View style={styles.sigLineCol}>
          <View style={styles.sigLine}>
            <Text style={styles.sigLineLabel}>NRIC (last 4)</Text>
          </View>
        </View>
        <View style={styles.sigLineCol}>
          <View style={styles.sigLine}>
            <Text style={styles.sigLineLabel}>Date</Text>
          </View>
        </View>
      </View>
    </View>
  );
}

export function TenancyAgreementDocument({ data }: { data: TenancyAgreementPdfData }) {
  const tenantLabel = data.tenantNames.length > 1 ? "Tenants" : "Tenant";
  return (
    <Document
      title={`Tenancy Agreement v${data.version} — ${data.property.address}`}
      author="RentOwl"
    >
      {/* Cover */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.coverTitle}>Tenancy Agreement</Text>
        <Text style={styles.coverSubtitle}>
          Version {data.version} · Generated {data.generatedAt}
        </Text>

        <Text style={styles.coverLabel}>Property</Text>
        <Text style={styles.coverValue}>
          {data.property.address} ({data.property.typeLabel})
        </Text>

        <View style={styles.coverRow}>
          <View style={styles.coverCol}>
            <Text style={styles.coverLabel}>Landlord</Text>
            <Text style={styles.coverValue}>{data.landlordName}</Text>
          </View>
          <View style={styles.coverCol}>
            <Text style={styles.coverLabel}>{tenantLabel}</Text>
            <Text style={styles.coverValue}>{data.tenantNames.join("\n")}</Text>
          </View>
        </View>

        <View style={styles.coverRow}>
          <View style={styles.coverCol}>
            <Text style={styles.coverLabel}>Term</Text>
            <Text style={styles.coverValue}>
              {data.term.startDate} to {data.term.endDate}
            </Text>
          </View>
          <View style={styles.coverCol}>
            <Text style={styles.coverLabel}>Rent / Deposit</Text>
            <Text style={styles.coverValue}>
              {data.term.monthlyRent}/mo · {data.term.deposit} deposit
            </Text>
          </View>
        </View>

        <Footer />
      </Page>

      {/* Clauses + signatures */}
      <Page size="A4" style={styles.page}>
        {data.clauses.map((clause) => (
          <View key={clause.clause_id} wrap>
            <Text style={styles.clauseTitle}>{clause.title}</Text>
            <ClauseBody body={clause.body} />
          </View>
        ))}

        <View break>
          <Text style={styles.sectionHeading}>Execution</Text>
          <Text style={styles.sigIntro}>
            Signed by the parties on the date written below.
          </Text>
          <SignatureBlock role="Landlord" name={data.landlordName} />
          {data.tenantNames.map((name, i) => (
            <SignatureBlock
              key={i}
              role={data.tenantNames.length > 1 ? `Tenant ${i + 1}` : "Tenant"}
              name={name}
            />
          ))}
        </View>

        <Footer />
      </Page>
    </Document>
  );
}
